# [START runtime]
application: sdapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"

builtins:
- django_wsgi: on

# # runtime: python
# # vm: true
# entrypoint: gunicorn -b :$PORT hellodjango.wsgi  

# runtime_config:
#   python_version: 2
# # [END runtime]

# handlers:
# - url: /.*
#   script: manage.py
