# [START runtime]
runtime: python
vm: true
entrypoint: gunicorn -b :$PORT hellodjango.wsgi

runtime_config:
  python_version: 2
# [END runtime]

builtins:
- django_wsgi: on

# handlers:
# - url: /.*
#   script: manage.py
