# [START runtime]
runtime: python27
api_version: 1
threadsafe: yes
version: 1


handlers:
- url: /static
  static_dir: static/
- url: .*
  script: mysite.wsgi.application

# # runtime: python
# # vm: true
# entrypoint: gunicorn -b :$PORT hellodjango.wsgi  

# runtime_config:
#   python_version: 2
# # [END runtime]

# handlers:
# - url: /.*
#   script: manage.py
